urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

admin.autodiscover()

"""
Basic, reusable patterns
"""
faculty = r'(?P<faculty>\w+)'
department = r'(?P<department>\w{4})'
number = '(?P<number>\d{3}[DNJ]?[123]?)'
course = department + '_' + number
page_type = '(?P<page_type>[^/]+)'
semester = '(?P<term>\w{4,6})-(?P<year>\d{4})'
slug = '(?P<slug>[^/]+)'
page = course + '/' + page_type + '/' + semester + '/' + slug
sha = '(?P<hash>[a-z0-9]{40})'
professor = '(?P<professor>[a-z-]*)'

"""
Begin mappings (URLs should be defined in order of descending priority (so highest priority first))
"""
direct_to_view = (
    ('main', (
        ('login', 'login_logout'),
        ('recent', 'recent'),
        ('recent/(?P<num_days>\d+)', 'recent'),
        ('recent/all', 'all_recent'),
        ('recent/all/(?P<num_days>\d+)', 'all_recent'),
        ('ucp', 'ucp'),
        ('ucp/(?P<mode>\w*)', 'ucp'),
        ('users/(?P<username>\w+)', 'profile'),
        ('users/(?P<username>\w+)/contributions', 'contributions'),
        ('search', 'search'),
        ('markdown', 'markdown'),
        ('register', 'register')
    )),
    ('messages', (
        ('messages', 'inbox'),
        ('messages/inbox', 'inbox'),
        ('messages/outbox', 'outbox'),
        ('messages/compose', 'compose'),
        ('messages/view/(?P<message_id>\d+)', 'view'),
    )),
    ('news', (
        ('news', 'main'),
        ('news/' + slug, 'view'),
    )),
    ('pages', (
        ('pages/random', 'random'),
        (course + '/create/' + page_type, 'create'),
        (page, 'show'),
        (page + '/edit', 'edit'),
        (page + '/history', 'history'),
        (page + '/print', 'printview'),
        #(page + '/raw', 'raw'),
        (page + '/commit/' + sha, 'commit'),
        #(page + '/inline', 'inline'),
    )),
    ('courses', (
        ('courses', 'index'),
        ('courses/create', 'create'),
        ('courses/all', 'all_browse'),
        ('courses/faculty', 'faculty_browse'),
        ('courses/department', 'department_browse'),
        ('courses/professor', 'professor_browse'),
        ('courses/popular', 'popular_browse'),
        ('courses/random', 'random'),
        ('courses/active', 'active_browse'),
        ('courses/get_all', 'get_all'),
        # Redirect department/number to department_number
        (department + '/' + number + '.*', 'remove_slash'),
        (course, 'overview'),
        (course + '/recent', 'recent'),
        (course + '/watch', 'watch'),
        (course + '/pin', 'pin'),
        (course + '/unpin', 'unpin'),
        (course + '/' + semester, 'semester_overview'),
        (course + '/' + page_type, 'category_overview'),
        (department, 'department_overview'),
        ('faculty/' + faculty, 'faculty_overview'),
        ('professor/' + professor, 'professor_overview'),
    )),
)

# Maps straight from about/history to the static view in main.py
static_urls = {
    'about': ['history', 'licensing', 'platform'], # the index one is implicit
    'contributing': ['moderating', 'development', 'content', 'guidelines'],
    'help': ['copyright', 'formatting', 'lexers'],
}

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
)

"""
Begin code for mapping the mappings
"""

# The index view has to be done separately
urlpatterns += patterns('',
    url(r'^$', 'views.main.index', name='home'),
)

for prefix, filenames in static_urls.iteritems():
    index_url = url(r'^' + prefix + '(?:/overview)?/$', 'views.main.static',
        {'mode': prefix, 'page': 'overview'}, name=prefix)
    urls = [url(r'^' + prefix + '/' + filename + '/$', 'views.main.static',
        {'mode': prefix, 'page': filename},
        name=prefix + '_' + filename) for filename in filenames]
    urlpatterns += patterns('', index_url, *urls)

for prefix, mapping in direct_to_view:
    urls = [url('^' + regex + '/$', view, name='%s_%s' % (prefix, view)) for regex, view in mapping]
    urlpatterns += patterns('views.' + prefix, *urls)

wiki/models/courses.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify

from wiki.models.history import HistoryItem
from wiki.utils.currents import current_year, current_term


class Course(models.Model):
    department = models.ForeignKey('Department')
    number = models.CharField(max_length=5, verbose_name="Course number")
    name = models.CharField(max_length=255)
    description = models.TextField(null=True)
    credits = models.DecimalField(max_digits=2, decimal_places=1,
        verbose_name="Number of credits") # Can be 4.5
    watchers = models.ManyToManyField(User, null=True, blank=True)
    # The latest_activity field makes it easier to sort and stuff ... not strictly necessary
    latest_activity = models.ForeignKey('HistoryItem',
        related_name='latest_course', null=True, blank=True)
    num_watchers = models.IntegerField(default=0) # caches it basically
    url_fields = {
        'department': 'department__short_name__iexact',
        'number': 'number',
    }

    class Meta:
        app_label = 'wiki'
        ordering = ['department__short_name', 'number']

    def __unicode__(self):
        return "%s %s" % (self.department.short_name, self.number)

    def get_absolute_url(self):
        return reverse('courses_overview', args=self.get_url_args())

    def increase_num_watchers_by(self, i):
        self.num_watchers += i
        self.save()

    def get_current_semester(self):
        try:
            return CourseSemester.objects.get(course=self, term=current_term, year=current_year)
        except CourseSemester.DoesNotExist:
            return None

    def get_url_args(self):
        return (self.department.pk, self.number)

    def get_recent_url(self):
        return reverse('courses_recent', args=self.get_url_args())

    def get_watch_url(self):
        return reverse('courses_watch', args=self.get_url_args())

    def get_pin_url(self):
        return reverse('courses_pin', args=self.get_url_args())

    def get_unpin_url(self):
        return reverse('courses_unpin', args=self.get_url_args())

    def num_pages(self):
        count = 0
        course_sems = self.coursesemester_set.all()
        for sem in course_sems:
            num_pages = sem.page_set.count()
            count += num_pages
        return count

    # Use this for adding an event to a course
    def add_event(self, user=None, action=None, page=None, message='',
        hexsha=None):
        new_item = HistoryItem(user=user, action=action, page=page, course=self,
            message=message, hexsha=hexsha)
        new_item.save()
        self.latest_activity = new_item
        self.save()

    # Get history items for this course; limited to 5 when called from the template
    # Set to 0 for no limit
    def recent_activity(self, limit=5):
        course_history = HistoryItem.objects.filter(course=self).order_by('-timestamp')
        if limit > 0:
            return course_history[:limit]
        else:
            return course_history


class CourseSemester(models.Model):
    course = models.ForeignKey('Course')
    evaluation = models.TextField(null=True, blank=True)
    professors = models.ManyToManyField('Professor', null=True, blank=True)
    midterm_info = models.TextField(null=True, blank=True)
    final_info = models.TextField(null=True, blank=True)
    readings = models.TextField(null=True, blank=True)
    term = models.CharField(max_length=6) # Winter/Summer etc
    year = models.IntegerField(max_length=4) # Because ... yeah
    url_fields = {
        'department': 'course__department__short_name__iexact',
        'number': 'course__number',
        'term': 'term',
        'year': 'year',
    }

    class Meta:
        app_label = 'wiki'
        unique_together = ('term', 'year', 'course')

    def __unicode__(self):
        return "%s (%s %d)" % (self.course, self.term.title(), self.year)

    def get_absolute_url(self):
        url_args = self.course.get_url_args() + (self.term, self.year)
        return reverse('courses_semester_overview', args=url_args)

    def get_semester(self):
        # For printing out. Returns Term year
        return "%s %d" % (self.term.title(), self.year)

    def get_slug(self):
        return "%s-%s" % (self.term, self.year)


class Professor(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    link = models.URLField(blank=True, null=True)
    url_fields = {
        'professor': 'slug',
    }

    class Meta:
        app_label = 'wiki'
        ordering = ['name']

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('courses_professor_overview', args=[self.slug])

    def get_courses(self):
        data = self.page_set.values('course_sem__course')
        course_ids = [k['course_sem__course'] for k in data]
        return Course.objects.filter(pk__in=course_ids)

wiki/models/departments.py
from django.core.urlresolvers import reverse
from django.db import models


class Department(models.Model):
    short_name = models.CharField(max_length=4, primary_key=True)
    long_name = models.CharField(max_length=255)
    faculty = models.ForeignKey('Faculty')
    url_fields = {
        'department': 'short_name__iexact',
    }

    class Meta:
        app_label = 'wiki'
        ordering = ['short_name']

    def __unicode__(self):
        return "Department of %s (%s)" % (self.long_name, self.short_name)

    def get_absolute_url(self):
        return reverse('courses_department_overview', args=[self.pk])

    def get_image(self):
        return "/static/img/department/%s.png" % self.short_name

    def get_large_image(self):
        return "/static/img/department/%s_large.png" % self.short_name

templates/courses/all.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <section>
        <div class="page-header">
            <h1>View all courses{% if mode %} :: By {{ mode }}{% endif %}</h1>
            <p>Tip: you can click on any table heading to sort by that column. Hold down the shift key and click on an additional heading to sort by multiple column.</p>
        </div>
        {% if courses %}
        <table class="zebra-striped">
            <thead>
                <tr>
                    <th width="10%">Course</th>
                    <th width="20%">Department</th>
                    <th width="20%">Faculty</th>
                    <th width="20%">Current professor(s)</th>
                    <th width="10%">Watching</th>
                    <th width="20%">Latest activity</th>
                </tr>
            </thead>
            <tbody>
                {% for course in courses %}
                <tr>
                    <td><a href="{{ course.get_absolute_url }}">{{ course }}</a></td>
                    <td><a href="{{ course.department.get_absolute_url }}">{{ course.department.long_name }}</ta></td>
                    <td><a href="{{ course.department.faculty.get_absolute_url }}">{{ course.department.faculty }}</a></td>
                    <td>None</td>
                    <td>{{ course.num_watchers }}</td>
                    <td>{{ course.latest_activity.timestamp|date:"F j Y f" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </section>
</div>
{% endblock %}

templates/courses/all_browse.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <section>
        <div class="page-header">
            <h1>{{ title }}</h1>
            <p>Tip: you can click on any table heading to sort by that column. Hold down the shift key and click on an additional heading to sort by multiple column.</p>
        </div>
        {% if courses %}
        <table class="zebra-striped">
            <thead>
                <tr>
                    <th width="10%">Course</th>
                    <th width="20%">Department</th>
                    <th width="20%">Faculty</th>
                    <th width="20%">Current professor(s)</th>
                    <th width="10%">Watching</th>
                    <th width="20%">Latest activity</th>
                </tr>
            </thead>
            <tbody>
                {% for course in courses %}
                <tr>
                    <td><a href="{{ course.get_absolute_url }}">{{ course }}</a></td>
                    <td><a href="{{ course.department.get_absolute_url }}">{{ course.department.long_name }}</ta></td>
                    <td><a href="{{ course.department.faculty.get_absolute_url }}">{{ course.department.faculty }}</a></td>
                    <td>None</td>
                    <td>{{ course.num_watchers }}</td>
                    <td>{{ course.latest_activity.timestamp|date:"F j Y f" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </section>
</div>
{% endblock %}

templates/courses/category.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <section>
        <ul class="breadcrumb">
             <li><a href="{{ course.get_absolute_url }}">{{ course }}</a> <span class="divider">&raquo;</span></li>
            <li class="active">{{ category.long_name }}</li>
        </ul>
        <div class="right-float">
            <a href="{{ create_url }}" class="btn danger">Create page</a>
        </div>
        <h1>Viewing category :: {{ category.long_name }}</h1>
        <hr />
        <br />
        {% if pages %}
        <table class="zebra-striped">
            <thead>
                <tr>
                    <th style="width: 60%;">Page</th>
                    <th style="width: 20%;">Semester</th>
                    <th style="width: 20%;">Professor</th>
                </tr>
            </thead>
            <tbody>
                {% for page in pages %}
                <tr>
                    <td>{% include page.get_type.get_cell_template %}</td>
                    <td><a href="{{ page.course_sem.get_absolute_url }}">{{ page.course_sem.get_semester }}</a></td>
                    <td>{% if page.professor %}<a href="{{ page.professor.get_absolute_url }}">{{ page.professor }}</a>{% else %}N/A{% endif %}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>No pages in this category.</p>
        {% endif %}
    </section>
</div>
{% endblock %}

templates/courses/category_overview.html
{% extends "base.html" %}

{% block og_image %}
<meta property="og:image" content="{{ site_url }}{{ course.department.get_large_image }}" />
{% endblock %}

{% block content %}
<div class="container">
    <section>
        <ul class="breadcrumb">
             <li><a href="{{ course.get_absolute_url }}">{{ course }}</a> <span class="divider">&raquo;</span></li>
            <li class="active">{{ category.long_name }}</li>
        </ul>
        <div class="right-float">
            <a href="{{ create_url }}" class="btn danger">Create page</a>
        </div>
        <h1>Viewing category :: {{ category.long_name }}</h1>
        <hr />
        <br />
        {% if pages %}
        <table class="zebra-striped">
            <thead>
                <tr>
                    <th style="width: 60%;">Page</th>
                    <th style="width: 20%;">Semester</th>
                    <th style="width: 20%;">Professor</th>
                </tr>
            </thead>
            <tbody>
                {% for page in pages %}
                <tr>
                    <td>{% include page.get_type.get_cell_template %}</td>
                    <td><a href="{{ page.course_sem.get_absolute_url }}">{{ page.course_sem.get_semester }}</a></td>
                    <td>{% if page.professor %}<a href="{{ page.professor.get_absolute_url }}">{{ page.professor }}</a>{% else %}N/A{% endif %}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>No pages in this category.</p>
        {% endif %}
    </section>
</div>
{% endblock %}

templates/courses/department.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<section>
		<div class="page-header">
			<h1>Courses - Browse by department</h1>
		</div>
		<div class="row">
			<div class="span16 columns">
				<p>Shows all the courses, listed alphabetically under the relevant department.</p>
				{% for dept in departments %}
				<h2>{{ dept.long }} <small><a href="/department/{{ dept.short }}">&raquo; View department page</a></small></h2>
				{% if dept.courses %}
					<ul class="unstyled">
					{% for course in dept.courses %}
						<li><a href="{{ course.url }}">{{ course }}</a></li>
					{% endfor %}
					</ul>
				{% else %}
				<p>No courses in this department</p>
				{% endif %}
				{% endfor %}
			</div>
		</div>
	</section>
</div>
{% endblock %}

templates/courses/department_browse.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <section>
        <div class="page-header">
            <h1>Courses - Browse by department</h1>
        </div>
        <div class="row">
            <div class="span16 columns">
                <p>Shows all the courses, listed alphabetically under the relevant department.</p>
                {% for dept in departments %}
                <h2>{{ dept.long_name }}
                    <small><a href="{{ dept.get_absolute_url }}">
                        &raquo; View department page
                    </a></small>
                </h2>
                {% with courses=dept.course_set.all %}
                    {% if courses.count %}
                        <ul class="unstyled">
                        {% for course in courses %}
                            <li><a href="{{ course.get_absolute_url }}">
                                {{ course }}
                            </a></li>
                        {% endfor %}
                        </ul>
                    {% else %}
                    <p>No courses in this department</p>
                    {% endif %}
                {% endwith %}
                {% endfor %}
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/courses/department_overview.html
{% extends "base.html" %}

{% block content %}
<div class="container"> 
    <section> 
        <div class="page-header">
            <h1>{{ dept.long_name }} ({{ dept.short_name }})</h1>
        </div>
        <br />
        <div class="row">
            <div class="span2 icon-thumb">
                <img src="{{ dept.get_image }}" title="{{ dept.long_name }}" />
            </div>
            <div class="span14 justify-align">
                <p><a href="{{ dept.faculty.get_absolute_url }}">{{ dept.faculty }}</a></p>
                <p><strong>{{ num_pages }}</strong> pages in <strong>{{ courses.count }}</strong> courses</p>
            </div>
        </div>
        <h2>Courses</h2>
        {% if courses %}
        <ul>
            {% for course in courses %}
            <li><a href="{{ course.get_absolute_url }}">{{ course }}</a></li>
            {% endfor %}
        </ul>
        {% endif %}
        <h2>Active contributors</h2>
        <p>List of people who have made a lot of edits to courses (maybe order in terms of deltas) in this department</p>
        <h2>Recent activity</h2>
        <p>List of recent edits/etc to courses in this department</p>
    </section> 
</div>
    
{% endblock %}

templates/courses/faculty.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<section>
		<div class="page-header">
			<h1>Courses - Browse by faculty</h1>
		</div>
		<div class="row">
			<div class="span16 columns">
				<p>Shows all the courses, listed alphabetically under the relevant faculty.</p>
				{% for faculty in faculties %}
				<h2>{{ faculty.name }} <small><a href="/faculty/{{ faculty.slug }}">&raquo; View faculty page</a></small></h2>
				{% if faculty.courses %}
					<ul class="unstyled">
					{% for course in faculty.courses %}
						<li><a href="{{ course.url }}">{{ course }}</a></li>
					{% endfor %}
					</ul>
				{% else %}
				<p>No courses in this faculty</p>
				{% endif %}
				{% endfor %}
			</div>
		</div>
	</section>
</div>
{% endblock %}

templates/courses/faculty_browse.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <section>
        <div class="page-header">
            <h1>Courses - Browse by faculty</h1>
        </div>
        <div class="row">
            <div class="span16 columns">
                <p>Shows all the courses, listed alphabetically under the relevant faculty.</p>
                {% for faculty, courses in faculties %}
                <h2>{{ faculty.name }} <small><a href="{{ faculty.get_absolute_url }}">&raquo; View faculty page</a></small></h2>
                {% if courses %}
                    <ul class="unstyled">
                    {% for course in courses %}
                        <li><a href="{{ course.get_absolute_url }}">{{ course }}</a></li>
                    {% endfor %}
                    </ul>
                {% else %}
                <p>No courses in this faculty</p>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/courses/faculty_overview.html
{% extends "base.html" %}

{% block content %}
<div class="container"> 
    <section> 
        <div class="page-header">
            <h1>{{ faculty }}</h1>
        </div>
        <div class="row">
            <div class="span2 center-align icon-thumb">
                <img src="{{ faculty.get_image }}" title="{{ faculty }}" />
            </div>
            <div class="span14">
                <p>{{ faculty }}</p>
            </div>
        </div>
        <h1>Departments</h1>
        <div class="row">
        {% for dept in departments %}
            <div class="span2 center-align icon-thumb">
                <a href="{{ dept.get_absolute_url }}"><img src="{{ dept.get_image }}" title="Department of {{ dept.long_name }} ({{ dept.short_name }})" /></a>
                <p><a href="{{ dept.get_absolute_url }}">{{ dept.short_name }}</a></p>
            </div>
        {% if forloop.counter|divisibleby:8 %}
            </div>
            <div class="row">
        {% endif %}
        {% empty %}
        <p>This faculty has no departments</p>
        {% endfor %}
        </div>
        <h1>Courses</h1>
        <div class="row">
        {% for course in courses %}
            <div class="span2 center-align icon-thumb">
                <a href="{{ course.get_absolute_url }}"><img src="{{ course.department.get_image }}" title="{{ course }} ({{ course.name }})" /></a>
                <p><a href="{{ course.get_absolute_url }}">{{ course }}</a></p>
            </div>
        {% if forloop.counter|divisibleby:8 %}
            </div>
            <div class="row">
        {% endif %}
        {% empty %}
        <p>This faculty also has no courses</p>
        {% endfor %}
        </div>
        <h2>Active contributors</h2>
        <p>List of people who have made a lot of edits to courses (maybe order in terms of deltas) in this faculty</p>
        <h2>Recent activity</h2>
        <p>List of recent edits/etc to courses in this faculty</p>
    </section> 
</div>
    
{% endblock %}

templates/courses/index.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
<div class="container">
    <section>
        <div class="page-header">
            <h1>Courses</h1>
        </div>
        <div class="row">
            <div class="span16 columns">
                <p>Here, you can browse our selection of courses by multiple criteria (faculty, department, semester, professor, etc). We currently have content for <strong>{{ num_courses }}</strong> courses in <strong>{{ num_departments }}</strong> departments.</p>
                {% if not user.is_authenticated %}
                <div class="alert-message success">
                    <p class="right-float">
                        <a href="{% url 'main_register' %}" class="btn">
                            Register an account &raquo;
                        </a>
                    </p>
                    <p><strong>Did you know</strong> that if you register, you can save courses to your profile and be notified of changes?</p>
                </div>
                {% endif %}
                <h2>Top 10 popular courses</h2>
                <p>
                    To view all the courses in our catalogue, sorted by
                    popularity (i.e. the number of watchers), <a
                    href="{% url 'courses_popular_browse' %}">click here</a>.
                </p>
                {% for course in popular_courses %}
                <p class="course-icons"><a href="{{ course.get_absolute_url }}"><img src="{{ course.department.get_image }}" alt="{{ course.department.short_name }}" title="{{ course }}" /></a><br /><a href="{{ course.get_absolute_url }}">{{ course }}</a></p>
                {% endfor %}
                <h2>Top 10 active courses</h2>
                <p>
                    To view all the courses in our catalogue, sorted by
                    activity, <a href="{% url 'courses_active_browse' %}">
                    click here</a>.
                </p>
                {% for course in active_courses %}
                <p class="course-icons"><a href="{{ course.get_absolute_url }}"><img src="{{ course.department.get_image }}" alt="{{ course.department.short_name }}" title="{{ course }}" /></a><br /><a href="{{ course.get_absolute_url }}">{{ course }}</a></p>
                {% endfor %}
                <h2>10 random courses</h2>
                <p>
                    We've selected 10 courses at random for your browsing
                    pleasure. Feel free to contribute by adding/editing content
                    if you know the material or, if you don't, proofreading or
                    something. You can also view a
                    <a href="{% url 'pages_random' %}">random page</a>
                    associated with a <a href="{% url 'courses_random' %}">
                    random course</a>.
                </p>
                {% for course in random_courses %}
                <p class="course-icons"><a href="{{ course.get_absolute_url }}"><img src="{{ course.department.get_image }}" alt="{{ course.department.short_name }}" title="{{ course }}" /></a><br /><a href="{{ course.get_absolute_url }}">{{ course }}</a></p>
                {% endfor %}
                <h2>Find a course</h2>
                <p>To find the course page for a course whose department and number (e.g. MATH 133) you know, simply enter it in the search box in the top left corner of the homepage.</p>
                <h2>Browse by faculty</h2>
                <p>
                    To view all the courses offered by each faculty in
                    alphabetical order, visit our <a
                    href="{% url 'courses_faculty_browse' %}">
                    browse-by-faculty page</a>.
                </p>
                <h2>Browse by department</h2>
                <p>
                    To view all the courses offered by each department in
                    alphabetical order, visit our <a
                    href="{% url 'courses_department_browse' %}">
                    browse-by-department page</a>.
                </p>
                <h2>Browse by professor</h2>
                <p>
                    To view all the courses offered by each professor in
                    alphabetical order, visit our <a
                    href="{% url 'courses_professor_browse' %}">
                    browse-by-professor page</a>.
                </p>
                <h2>View all courses</h2>
                <p>
                    Are you really just looking for an alphabetical listing of
                    every course in our catalogue? If so, you're in luck. <a
                    href="{% url 'courses_all_browse' %}">View all courses
                    &raquo;</a>
                </p>
                <h2>Create a course</h2>
                <p>Want to add content for a course we don't yet have in our catalogue? <a href="{% url "courses_create" %}">Create a new course &raquo;</a></p>
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/courses/professor.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <section>
        <div class="page-header">
            <h1>Courses - Browse by professor</h1>
        </div>
        <div class="row">
            <div class="span16 columns">
                <p>Shows all the courses, listed alphabetically under the relevant professor.</p>
                {% for dept in departments %}
                <h2>{{ dept.long }} <small><a href="/{{ dept.short }}">&raquo; View department page</a></small></h2>
                {% if dept.courses %}
                    <ul class="unstyled">
                    {% for course in dept.courses %}
                        <li><a href="{{ course.get_absolute_url }}">{{ course }}</a></li>
                    {% endfor %}
                    </ul>
                {% else %}
                <p>No courses in this department</p>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/courses/professor_overview.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <section>
        <div class="page-header">
            <h1>Professor details &mdash; {{ professor }}</h1>
        </div>

        {% if professor.link %}
        <p><strong>Personal webpage</strong>: <a href="{{ professor.link }}">{{ professor.link }}</a>
        {% endif %}

        <h2>Associated pages</h2>
        {% if pages %}
        <table class="zebra-striped centered">
            <thead>
                <tr>
                    <th>Department</th>
                    <th>Course</th>
                    <th>Semester</th>
                    <th>Page</th>
                </tr>
            </thead>
            <tbody>
                {% for page in pages %}
                {% with course=page.course_sem.course %}
                <tr>
                    <td><a href="{{ course.department.get_absolute_url }}"><img src="{{ course.department.get_image }}" alt="{{ course.department.short_name }}" title="{{ course.department }}" /></a></td>
                    <td>
                        <a href="{{ course.get_absolute_url }}">
                        {{ course }} ({{ course.name }})
                        </a>
                    </td>
                    <td>{{ page.course_sem.get_semester }}</td>
                    <td><a href="{{ page.get_absolute_url }}">{{ page }}</a></td>
                </tr>
                {% endwith %}
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>There are no pages associated with this professor.</p>
        {% endif %}
    </section>
</div>
{% endblock %}